name: Deploy Game to Itch.io

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pyinstaller  # Instalar PyInstaller para crear el ejecutable

      - name: Construcción del juego
        run: |
          pyinstaller --onefile --windowed --name=umei main.py

      - name: Comprimir el ejecutable en un ZIP
        run: |
          zip -r umei.zip dist/umei.exe assets/ screens/ tilemap/ player.py camera.py intro.py enemies.py consumable.py dialog.py requirements.txt

      - name: Instalar Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          sudo mv butler /usr/local/bin/

      - name: Desplegar el juego en Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: butler push umei.zip wachopuffs/umei:windows
